### ISSUE TITLE
0.2.0 client exception after connecting to host

### ISSUE THREAD

**Issue by redspot** [spacechase0/StardewValleyMP#15]
here's the error from 0.2.0 causing the clients to hang.

to reproduce:
[host]
start StardewModdingAPI.exe
chose savefile
chose host
listen for clients
[client]
chose savefile
connect to host
#client throws exception after successful network connection
#and the host does not have to start the game

stardew valley 1.07 - product 1.0.5940.30711
smapi 0.40.0 from cjsu/SMAPI
makeshift multiplayer 0.2.0

[01:26:57.101 PM] Exception receiving: System.IO.IOException: The process cannot access the file 'C:\Users\xxxxxx\AppData\Roaming\StardewValley\Saves\redspot_119326892\redspot_119326892' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at StardewValleyMP.Packets.YourIDPacket.process(Client client) in c:\Users\Chase\Documents\Visual Studio 2013\Projects\StardewValleyMP\StardewValleyMP\Packets\YourIDPacket.cs:line 64
   at StardewValleyMP.Client.update() in c:\Users\Chase\Documents\Visual Studio 2013\Projects\StardewValleyMP\StardewValleyMP\Client.cs:line 105
[01:26:57.104 PM] Initial loading done

the file is not likely in use. we tried with clean installs, verified cache, new characters. let me know if you need more info.

**Comment by spacechase0** [comment]
Is it fixed in 0.2.2?

**Comment by spacechase0** [comment]
Someone else said it is. The error still shows up (which I know would happen), but it connects after that.
